name: moltbot-pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # 每4小时一次（UTC）。如果你要更频繁可改 */3

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      MOLTBOOK_API_KEY: ${{ secrets.MOLTBOOK_API_KEY }}
      MOLTBOOK_HANDLE: ${{ secrets.MOLTBOOK_HANDLE }}
      # 可选：控制 pre-digest 输出规模
      PRE_DIGEST_THREADS: "4"
      PRE_DIGEST_HEAD: "3"
      PRE_DIGEST_HOT: "8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Run pipeline
        run: |
          node collect.js
          node tag-keywords.js
          node keyword-index.js
          node deep-dive.js
          node auto-hot-export.js
          node pre-digest.js
          node timeline.js
          # 如果你有 pins 体系也想在云端跑：
          if [ -f pins.txt ]; then node export-pins.js; node pins-pack.js; fi

      - name: Commit outputs
        run: |
          git config user.name "moltbot-bot"
          git config user.email "moltbot-bot@users.noreply.github.com"
          git add reports exports
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "pipeline: $(date -u +'%Y-%m-%d %H:%M UTC')"
            git push
          fi
